pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                echo 'Clonage du code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'cd backend && ./mvnw clean package -DskipTests'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'cd backend && docker build -t jiralite-app .'
            }
        }

        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'cd backend && docker compose up -d --build'
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline réussi !'
        }
        failure {
            echo '❌ Pipeline échoué !'
        }
    }
}