piplines{
agent any
  stages{
  stage('Clone') {
                     steps {
                         echo 'Clonage du code...'
                         checkout scm
                     }
     }
      stage('Build & Test') {
                 steps {
                     echo 'Build Maven...'
                     sh 'cd backend && ./mvnw clean package -DskipTests'
                 }
             }

             }
}